server:
  port: 8081

spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      authentication-database: admin
      uri: mongodb://localhost:27017/webShopSecurityDB?readPreference=primary&appname=MongoDB%20Compass&ssl=false
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

application:
  jwt:
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: '14'
    secretKey: ${JWT_SECRET_KEY}



